version: '2'
services:
  rstudio: 
    environment:
      - USER=rstudio
      - PASSWORD=qwerty
    image: gcr.io/ml-learning-199501/github.com/jasonmhoule/rc-alexandria:8f37315	
    ports:
      - "8787:8787"
    links:
      - selenium:selenium
  selenium:
    image: selenium/standalone-chrome:3.141
    ports:
      - "4444:4444"
